{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rig.fullname" . }}
  labels:
    {{- include "rig.labels" . | nindent 4 }}
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_SECRET: {{ required "secrets.oauthClientSecret is required when not using existingSecret" .Values.secrets.oauthClientSecret | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ required "secrets.oauthCookieSecret is required when not using existingSecret" .Values.secrets.oauthCookieSecret | quote }}
{{- end }}
