apiVersion: v2
name: rig
description: Music library management UI with integrated backends
version: 0.1.6
appVersion: "0.1.6"
type: application
dependencies:
  - name: preamp
    version: "0.2.4"
    repository: "oci://ghcr.io/benrachmiel/preamp/charts"
    condition: preamp.enabled
  - name: gain-downloader
    version: "0.2.1"
    repository: "oci://ghcr.io/benrachmiel/gain/charts"
    condition: gain-downloader.enabled
